name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI / routing / state
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # networking
  dio: ^5.5.0+1
  http: ^1.2.2

  # storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # model generation (optional แต่ดี)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # codegen
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/thai_admin.json